// <auto-generated />
using System;
using Dino.ReservationsService.Api.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dino.ReservationsService.Api.DAL.Migrations
{
    [DbContext(typeof(ReservationsDbContext))]
    [Migration("20250518105842_UpdateReservationModel2")]
    partial class UpdateReservationModel2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dino.ReservationsService.Api.DAL.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CheckIn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOut")
                        .HasColumnType("date");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "CheckIn", "CheckOut");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa5d6369-b31a-45d9-b39d-e1e2288818fa"),
                            CheckIn = new DateOnly(2025, 5, 18),
                            CheckOut = new DateOnly(2025, 5, 20),
                            GuestId = new Guid("fd0fb19a-8242-4c87-bb93-386e1a61552e"),
                            RoomId = new Guid("5df24c2f-3738-4920-a403-815dfa4a85dd"),
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = new Guid("c2592960-d746-4309-954f-2c88c1d0dc21"),
                            CheckIn = new DateOnly(2025, 6, 1),
                            CheckOut = new DateOnly(2025, 6, 8),
                            GuestId = new Guid("f11bb0d5-31a3-4cc5-82f8-a2f224295d42"),
                            RoomId = new Guid("a2905bdd-34bb-45e2-b1cd-1180159fde08"),
                            Status = "Confirmed"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
