// <auto-generated />
using System;
using Dino.ReservationsService.Api.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dino.ReservationsService.Api.DAL.Migrations
{
    [DbContext(typeof(ReservationsDbContext))]
    [Migration("20250518105125_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dino.ReservationsService.Api.DAL.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CheckIn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOut")
                        .HasColumnType("date");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "CheckIn", "CheckOut");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39ae7df2-8595-40f8-b611-f6558fa55739"),
                            CheckIn = new DateOnly(2025, 5, 18),
                            CheckOut = new DateOnly(2025, 5, 21),
                            GuestId = new Guid("ad9f0527-18f6-4485-9ee9-df9637c34f03"),
                            RoomId = new Guid("0dde4b79-7674-4b5d-bb77-88dcced2712a"),
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = new Guid("7ad8df20-6cf8-4c3a-ad44-ae2a655a4453"),
                            CheckIn = new DateOnly(2025, 5, 23),
                            CheckOut = new DateOnly(2025, 5, 28),
                            GuestId = new Guid("f354fd2a-08ce-476d-a6c5-c72aee917e0e"),
                            RoomId = new Guid("62d0d84b-fb81-41fd-bcae-573393db6fd0"),
                            Status = "Confirmed"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
